export const DEFAULT_MODE = "strict";
export const API_SEARCH = "/search";
export const HISTORY_KEY = "agda_search_history";

export const SYMBOL_MAP = {
  "\\->": "→",
  "\\=>": "⇒",
  "\\forall": "∀",
  "\\==": "≡",
  "\\leq": "≤",
  "\\geq": "≥",
  "\\times": "×",
  "\\lambda": "λ",
  "\\bot": "⊥",
  "\\top": "⊤",
  "\\neg": "¬",
  "\\in": "∈",
  "\\and": "∧",
  "\\or": "∨",
  "\\union": "∪",
  "\\approx": "≈",
  "\\identical": "≣",
  "\\subset": "⊂",
  "\\supset": "⊃",
  "\\subseteq": "⊆",
  "\\uplus": "⊎",
  "\\turnstile": "⊢",
  "\\Gamma": "Γ",
  "\\N": "ℕ",
  "\\bullet": "●",
  "\\prime": "′",
  "\\sub0": "₀",
  "\\sub1": "₁",
  "\\sub2": "₂",
  "\\sub3": "₃",
  "\\phi": "ϕ",
  "\\psi": "ψ",
  "\\sigma": "σ",
  "\\iota": "ι",
  "\\epsilon": "ε",
  "\\dot": "·",
  "\\triangleright": "▷",
  "\\triangleleft": "◁",
  "\\langle": "⟨",
  "\\rangle": "⟩",
  "\\llbracket": "⟦",
  "\\rrbracket": "⟧",
  "\\lcustom": "⟅",
  "\\rcustom": "⟆",
  "\\downarrow": "↓",
  "\\join": "⧺",
  "\\relcomp": "⨾",
  "\\leqq": "⩽",
  "\\dbl1": "𝟙",
  "\\dbl2": "𝟚",
  "\\bB": "𝔹",
  "\\bZ": "ℤ",
  "\\o+": "⊕",
  "\\O+": "⨁",
  "\\{{": "⦃",
  "\\}}": "⦄",
};
